### ISSUE TITLE
Issue: Dimension Monitor Shows Current Dimension Info in NEI

### ISSUE THREAD

**Issue by tylerjcw** [McJtyMods/RFTools#313]
This is a issue / exploit I noticed last night while crafting a Dimension Monitor - When you look at the Dimension Monitor in NEI, you can see the current power level of the dimension you are in (live-updating also). This pretty much eliminates the need to craft the item, instead just open NEI and search for it. One way I would suggest fixing this is making the dimension monitor have a UI that is opened while it is held in your hand. Have the UI display some more detailed info about the dimension (maybe show the dimlets used to create the dimension, along with the current power level and +-RF/t). This would eliminate the need for the progress bar (on the texture) and tooltip info, and alleviate the need of trying to remember what dimlets are used in your dimension

![2015-09-02_03 39 16](https://cloud.githubusercontent.com/assets/413916/9625459/4d224d46-5124-11e5-809a-a4c66ec7d60d.png)

**Comment by McJty** [comment]
I know about this issue but the proposed solution is not acceptable. This item is useful because you can keep it in your hotbar and you can see at a glance what the current status is. I personally rather have this item work in NEI then get rid of that feature. It would be nice if I could detect if the item is in NEI and not in a real inventory and if so prevent it from being usable but I don't know if that's possible.

**Comment by tylerjcw** [comment]
Maybe try a charged / uncharged version? only show the uncharged version in NEI (a config option maybe) and have the item use a very low amount of RF/t.

**Comment by McJty** [comment]
Yes, that may be a solution. Good idea.

**Comment by tylerjcw** [comment]
Thank you. I still would like to suggest adding the +-RF/t to the tooltip though. That makes it a bit easier to gauge your power usage.

**Comment by MichaelHillcox** [comment]
Please reopen this issue if this is still an issue with `JEI` in 1.12. Thanks :D
