### ISSUE TITLE
World break on quarry card mistake

### ISSUE THREAD

**Issue by Zaflis** [McJtyMods/RFTools#380]
I get disconnected each time trying, after i put quarry card in shield projector and click it. Card was set to solid sphere of (33, 44, 33) size, centered at 0. I tried quarry card before with Builder block and it works in there, now just wanted for some reason to see what happens. When i open world in MCEdit i see a huge solid sphere of tile entities i can't even imagine to remove, i will have to recall a world backup.

So i guess you shouldn't allow certain cards inside projector, or make them just do nothing?

PS. Missing a solid topdome shape for making underwater base :p  Sphere makes an extra basement for me though, assuming it will remove water blocks. Either quarry or void card should.

**Comment by McJty** [comment]
Hmmm, a quarry card in the shield should be no problem normally. It would work as a normal card. What could be the problem is that the number of blocks was too high for the shield. What happens if you tried to load that world? How is the world broken? A crashlog would be useful

Topdome is one of the shapes that is there. Why do you think it is missing?

**Comment by Zaflis** [comment]
No crashlog, server stays up and client just disconnects to menu. I think it was something about too big packet size.

I couldn't find *Solid* topdome. Normal topdome is there to make just the border. I can use that to keep water from flowing in after voiding insides.

**Comment by McJty** [comment]
It might possible to uncorrupt your world by temporarily setting     B:disableShieldBlocksToUncorruptWorld=true in the config. Removing the card from the shield and then restore that setting
