### ISSUE TITLE
Interaction issue after teleporting with rftools

### ISSUE THREAD

**Issue by LewisLarsen** [McJtyMods/RFTools#862]
I'm playing on the Direwolf20 1.10.2 pack on a server and there's this weird interaction bug that happens after teleporting from the End to my base. 

I teleport to my base and I cannot break any blocks, I cannot use pressure plates and other players say they can't see me. The only way to fix this is to reconnect to the server. This doesn't happen all the time but it's annoying when it does.

**Comment by McJty** [comment]
Weird. I never have this issue in my LP where I also go from the end to the overworld using RFTools teleporters regularly. I have no explanation.

**Comment by Medusalem** [comment]
We have that too, but that is not A problem of RF tools, happens also with the Mod "Waystones" and the Teleporter funktions of Draconic Evolution! 

Waystones way more often than RF Tools and Rf Tools more often than Draconic Evolution, but that's maybe because everyone is using Waystones... but thats the Informations i have

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
